platform :ios, '9.0'
use_frameworks!

target "XHWLHouseManager" do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'IQKeyboardManagerSwift'
pod 'swiftScan'
pod 'SnapKit'
pod 'XHToastSwift'

end
